name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]

defaults:
  run:
    shell: "bash"

jobs:
  build:
    steps:
      - uses: "actions/checkout@v2"

      - uses: "actions/setup-node@v2"
        with:
          node-version: "14.x"

      - run: node test/indx.js
